branches:
  only:
  - master

language: cpp
compiler:
  - clang
  - gcc

script:
- cd dmc && mkdir build && cd build && cmake .. && make -j3
#- cd dme && mkdir build && cd build && cmake .. && make -j3
