branches:
  only:
    - master
    - ci # CI testing


language: generic  # Avoid system resetting CC/CXX before install

dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8 # Install newer libstdc++ also required by clang

matrix:
  include:
    - compiler: gcc-8
      env: CC=gcc-8 CXX=g++-8

    - compiler: clang
      env: CC=clang CXX=clang++

script:
  # DMC
  - cd dmc && mkdir build && cd build && cmake .. && make -j3
  # DME
  #- cd dme && mkdir build && cd build && cmake .. && make -j3
